#include "topolang.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

bool topo_export_obj_ex(const TopoScene *scene, const char *outObjPath, int triangulate, TopoError *err) {
    FILE *f = fopen(outObjPath, "wb");
    if (!f) {
        if (err) {
            err->line = 0;
            err->col = 0;
            strcpy(err->msg, "can't write obj");
        }
        return false;
    }

    fprintf(f, "# OBJ generated by Topolang\n");

    int base = 0;
    for (int mi = 0; mi < scene->count; mi++) {
        const TopoMesh *m = &scene->meshes[mi];

        fprintf(f, "o mesh_%d\n", mi);

        for (int i = 0; i < m->vCount; i++) {
            const float *p = &m->vertices[i * 3];
            fprintf(f, "v %.9g %.9g %.9g\n", (double) p[0], (double) p[1], (double) p[2]);
        }

        if (triangulate) {
            for (int qi = 0; qi < m->qCount; qi++) {
                int a = m->quads[qi * 4 + 0] + base + 1;
                int b = m->quads[qi * 4 + 1] + base + 1;
                int c = m->quads[qi * 4 + 2] + base + 1;
                int d = m->quads[qi * 4 + 3] + base + 1;
                fprintf(f, "f %d %d %d\n", a, b, c);
                fprintf(f, "f %d %d %d\n", a, c, d);
            }
        } else {
            for (int qi = 0; qi < m->qCount; qi++) {
                int a = m->quads[qi * 4 + 0] + base + 1;
                int b = m->quads[qi * 4 + 1] + base + 1;
                int c = m->quads[qi * 4 + 2] + base + 1;
                int d = m->quads[qi * 4 + 3] + base + 1;
                fprintf(f, "f %d %d %d %d\n", a, b, c, d);
            }
        }

        base += m->vCount;
    }

    fclose(f);
    return true;
}

bool topo_export_obj(const TopoScene *scene, const char *outObjPath, TopoError *err) {
    return topo_export_obj_ex(scene, outObjPath, 0, err);
}
